service: aws-sls-lambda-ts-template
frameworkVersion: "2"
provider:
  name: aws
  region: eu-central-1
  runtime: nodejs14.x

functions:
  main:
    handler: handler.main
    timeout: 30
    events:
      - http:
          path: test
          method: get

package:
  excludeDevDependencies: false
  individually: true

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-plugin-scripts
  - serverless-dotenv-plugin
  - serverless-plugin-common-excludes
  - serverless-plugin-include-dependencies

custom:
  serverlessPluginTypescript:
    tsConfigFileLocation: "./tsconfig.json"
