service: ts-lambda-template
frameworkVersion: "2"
provider:
  name: aws
  region: eu-central-1
  runtime: nodejs14.x

functions:
  main:
    handler: handler.main
    timeout: 30
    events:
      - http:
          path: test
          method: get

plugins:
  - serverless-offline
  - serverless-plugin-scripts
  - serverless-dotenv-plugin

custom:
  scripts:
    hooks:
      "before:package:initialize": npm run build
